# Generated by Django 4.1.7 on 2023-02-19 06:32

import app_sisfocvwaero.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_sisfocvwaero", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Divisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("divisi", models.CharField(max_length=30)),
                ("gapok", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Karyawan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nip", models.CharField(max_length=30)),
                ("nama", models.CharField(max_length=50)),
                ("jk", models.CharField(max_length=30, null=True)),
                (
                    "agama",
                    models.CharField(
                        choices=[
                            ("ISLAM", "ISLAM"),
                            ("PROTESTAN", "PROTESTAN"),
                            ("KATOLIK", "KATOLIK"),
                            ("HINDU", "HINDU"),
                            ("BUDHA", "BUDHA"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("tgl_lahir", models.DateField()),
                ("tmpt_lahir", models.CharField(max_length=50)),
                (
                    "pendidikan",
                    models.CharField(
                        choices=[
                            ("STRATA 2", "STRATA 2"),
                            ("STRATA 1", "STRATA 1"),
                            ("SMA/SMK/SEDERAJAT", "SMA/SMK/SEDERAJAT"),
                            ("SMP/MTS/SEDERAJAT", "SMP/MTS/SEDERAJAT"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("alamat", models.CharField(max_length=50)),
                ("nohp", models.CharField(max_length=50)),
                (
                    "foto",
                    models.ImageField(
                        null=True,
                    ),
                ),
                (
                    "divisi_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_sisfocvwaero.divisi",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
