# Generated by Django 4.1.7 on 2023-02-19 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_sisfocvwaero", "0002_divisi_karyawan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="karyawan",
            name="divisi_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_sisfocvwaero.divisi",
            ),
        ),
    ]
