# Generated by Django 4.1.7 on 2023-02-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sisfocvwaero", "0007_alter_karyawan_alamat_alter_karyawan_foto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="karyawan",
            name="foto",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
    ]
