# Generated by Django 4.1.7 on 2023-02-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sisfocvwaero", "0008_alter_karyawan_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Absensi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_location", models.CharField(max_length=200)),
                ("office", models.CharField(max_length=200)),
                ("distance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tanggal", models.DateTimeField(auto_now_add=True)),
                ("absen_masuk", models.TimeField(auto_now_add=True)),
                ("ket_masuk", models.CharField(max_length=30)),
                ("absen_keluar", models.TimeField(auto_now_add=True)),
                ("ket_keluar", models.CharField(max_length=30)),
                ("status", models.CharField(max_length=30)),
            ],
        ),
    ]
