# Generated by Django 4.1.7 on 2023-02-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_sisfocvwaero", "0009_absensi"),
    ]

    operations = [
        migrations.RenameField(
            model_name="absensi",
            old_name="user_location",
            new_name="location",
        ),
    ]
