# Generated by Django 4.1.7 on 2023-02-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sisfocvwaero", "0010_rename_user_location_absensi_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absensi",
            name="tanggal",
            field=models.DateField(auto_now_add=True),
        ),
    ]
