# Generated by Django 4.1.7 on 2023-02-27 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_sisfocvwaero", "0011_alter_absensi_tanggal"),
    ]

    operations = [
        migrations.AddField(
            model_name="absensi",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
