# Generated by Django 4.1.7 on 2023-03-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sisfocvwaero", "0012_absensi_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="absensi",
            name="distance",
        ),
        migrations.RemoveField(
            model_name="absensi",
            name="location",
        ),
        migrations.RemoveField(
            model_name="absensi",
            name="office",
        ),
        migrations.AddField(
            model_name="absensi",
            name="image_keluar",
            field=models.ImageField(null=True, upload_to="image_keluar/"),
        ),
        migrations.AddField(
            model_name="absensi",
            name="image_masuk",
            field=models.ImageField(null=True, upload_to="image_masuk/"),
        ),
    ]
