# Generated by Django 4.1.7 on 2023-03-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_sisfocvwaero",
            "0013_remove_absensi_distance_remove_absensi_location_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="absensi",
            name="image_keluar",
            field=models.ImageField(
                default=False, null=True, upload_to="image_keluar/"
            ),
        ),
    ]
