# Generated by Django 4.1.7 on 2023-03-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sisfocvwaero", "0014_alter_absensi_image_keluar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Capture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="captures")),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
