# Generated by Django 4.1.7 on 2023-03-08 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_sisfocvwaero", "0015_capture"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Capture",
            new_name="Gambar",
        ),
    ]
