# Generated by Django 4.1.7 on 2023-03-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sisfocvwaero", "0016_rename_capture_gambar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absensi",
            name="image_keluar",
            field=models.ImageField(null=True, upload_to="image_keluar/"),
        ),
    ]
