# Generated by Django 4.1.7 on 2023-03-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sisfocvwaero", "0017_alter_absensi_image_keluar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absensi",
            name="absen_keluar",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="absensi",
            name="absen_masuk",
            field=models.TimeField(),
        ),
    ]
