# Generated by Django 4.1.7 on 2023-03-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_sisfocvwaero",
            "0018_alter_absensi_absen_keluar_alter_absensi_absen_masuk",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="absensi",
            name="jml_jamlembur",
            field=models.IntegerField(null=True),
        ),
    ]
