# Generated by Django 4.1.7 on 2023-03-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sisfocvwaero", "0019_absensi_jml_jamlembur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absensi",
            name="absen_keluar",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="absensi",
            name="absen_masuk",
            field=models.TimeField(null=True),
        ),
    ]
