# Generated by Django 4.1.7 on 2023-03-12 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_sisfocvwaero",
            "0020_alter_absensi_absen_keluar_alter_absensi_absen_masuk",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="absensi",
            name="ket_keluar",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="absensi",
            name="ket_masuk",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name="Sakit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keterangan", models.CharField(max_length=100, null=True)),
                ("foto", models.ImageField(null=True, upload_to="sakit/")),
                (
                    "absensi",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_sisfocvwaero.absensi",
                    ),
                ),
            ],
        ),
    ]
